DEFAULT_QR = [
        {
            "area_name":"S1",
            "horizontal_coordinate":8000.0,
            "vertical_coordinate":12500.0
        },
        {
            "area_name":"S2",
            "horizontal_coordinate":8000.0,
            "vertical_coordinate":0.0
        },
        {
            "area_name":"A",
            "horizontal_coordinate":13250.0,
            "vertical_coordinate":6250.0
        },
        {
            "area_name":"B",
            "horizontal_coordinate":10625.0,
            "vertical_coordinate":6250.0,
        },
        {
            "area_name":"C",
            "horizontal_coordinate":5375.0,
            "vertical_coordinate":6250.0
        },
        {
            "area_name":"D",
            "horizontal_coordinate":2750.0,
            "vertical_coordinate":6250.0
        },
        {
            "area_name":"1",
            "horizontal_coordinate":0,
            "vertical_coordinate":0
        },
        {
            "area_name":"2",
            "horizontal_coordinate":0,
            "vertical_coordinate":12500.0
        },
        {
            "area_name":"3",
            "horizontal_coordinate":16000.0,
            "vertical_coordinate":12500.0
        },
        {
            "area_name":"4",
            "horizontal_coordinate":16000.0,
            "vertical_coordinate":0
        }
]
