DEFAULT_QR = [
        {
            "area_name":"S1",
            "vertical_coordinate":0,
            "horizontal_coordinate":0
        },
        {
            "area_name":"S2",
            "vertical_coordinate":0,
            "horizontal_coordinate":0
        },
        {
            "area_name":"A",
            "vertical_coordinate":0,
            "horizontal_coordinate":0
        },
        {
            "area_name":"B",
            "vertical_coordinate":0,
            "horizontal_coordinate":0
        },
        {
            "area_name":"C",
            "vertical_coordinate":0,
            "horizontal_coordinate":0
        },
        {
            "area_name":"D",
            "vertical_coordinate":0,
            "horizontal_coordinate":0
        },
        {
            "area_name":"1",
            "vertical_coordinate":0,
            "horizontal_coordinate":0
        },
        {
            "area_name":"2",
            "vertical_coordinate":0,
            "horizontal_coordinate":0
        },
        {
            "area_name":"3",
            "vertical_coordinate":0,
            "horizontal_coordinate":0
        },
        {
            "area_name":"4",
            "vertical_coordinate":0,
            "horizontal_coordinate":0
        }
]
